const Log = require("./logger");

// Paste your access token below
const TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiYXVkIjoiaHR0cDovLzIwLjI0NC41Ni4xNDQvZXZhbHVhdGlvbi1zZXJ2aWNlIiwiZW1haWwiOiJoYXJzaGl0aGF0c3MyM0BnbWFpbC5jb20iLCJleHAiOjE3ODA2MzgxNDksImlhdCI6MTc4MDYzNzI0OSwiaXNzIjoiQWZmb3JkIE1lZGljYWwgVGVjaG5vbG9naWVzIFByaXZhdGUgTGltaXRlZCIsImp0aSI6IjEwMTRlNzFhLThmMjAtNGQzZC05MzhmLTI4MjY2NWExNzM1ZSIsImxvY2FsZSI6ImVuLUlOIiwibmFtZSI6InRpbW1hcmFqdXBhbGVtIHNhaSBzcmkgaGFyc2hpdGhhIiwic3ViIjoiMjllYmY0OTEtOTk1Mi00ZjlkLThiNzQtOWFiZDMyNWNkZGJlIn0sImVtYWlsIjoiaGFyc2hpdGhhdHNzMjNAZ21haWwuY29tIiwibmFtZSI6InRpbW1hcmFqdXBhbGVtIHNhaSBzcmkgaGFyc2hpdGhhIiwicm9sbE5vIjoiMjNicTFhNDc5OSIsImFjY2Vzc0NvZGUiOiJRUWRFWXkiLCJjbGllbnRJRCI6IjI5ZWJmNDkxLTk5NTItNGY5ZC04Yjc0LTlhYmQzMjVjZGRiZSIsImNsaWVudFNlY3JldCI6IkN5RG5UQm1RSHhmWlJ6cFIifQ.ng02INuHcuBz8t14nn2-1kImC6uhbJ3fJc5wlFHAYCM";

Log(
    "frontend",
    "info",
    "component",
    "Logging middleware test successful",
    TOKEN
);